In [58]:
import tensorflow as tf

In [59]:
tf.__version__

'2.15.0'

In [60]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim) #number of dimensions

tf.Tensor(7, shape=(), dtype=int32)
0


In [61]:
vector = tf.constant([26,12])
print(vector)
print(vector.ndim) #number of dimensions

tf.Tensor([26 12], shape=(2,), dtype=int32)
1


In [62]:
matrix = tf.constant([[26,12],[9,11]])
print(matrix)
print(matrix.ndim) #number of dimensions

tf.Tensor(
[[26 12]
 [ 9 11]], shape=(2, 2), dtype=int32)
2


In [63]:
matrix = tf.constant([[26,12],[9,11]],dtype =tf.float16) #chnaging dtype
print(matrix)
print(matrix.ndim) #number of dimensions

tf.Tensor(
[[26. 12.]
 [ 9. 11.]], shape=(2, 2), dtype=float16)
2


# tf.Variable()

In [64]:
changeable_tensor = tf.Variable([13, 34])
unchanageble = tf.constant([12,26])

In [65]:
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([13, 34], dtype=int32)>


In [66]:
# changeable_tensor.append([12,26]) ..........NO append works for this instead use assign
# print(changeable_tensor)

In [67]:
# Now you can use .assign()
changeable_tensor[0].assign(12,67)
print(changeable_tensor)

# We can use assign() on unchanagable tensors or constants which are specially designed to keep the tensor value consistent

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12, 34], dtype=int32)>


### Random Tensor

In [68]:
random = tf.random.Generator.from_seed(8)
random =random.normal(shape=(10,20)) # distributions can be normal , uniform
print(random)

tf.Tensor(
[[ 0.69211644  0.84215707 -0.06378496  0.92800784 -0.6039789  -0.1766927
   0.04221033  0.29037967 -0.29604465 -0.21134205  0.01063002  1.5165398
   0.27305737 -0.29925638 -0.3652325   0.61883307 -1.0130816   0.28291714
   1.2132233   0.46988967]
 [ 0.37944323 -0.6664026   0.6054596   0.19181173  0.8045827   0.4769051
  -0.7812124  -0.996891    0.33149973 -0.5445254   1.5222508   0.59303206
  -0.63509274  0.3703566  -1.0939722  -0.4601445   1.5420506  -0.16822556
  -0.4390865  -0.4129243 ]
 [ 0.35877243 -1.9095894  -0.2094769   0.8286217  -0.06695071 -0.35105535
   1.0884082  -1.3863064   0.88051325 -1.6833194   0.86754173 -0.19625713
  -1.322665   -0.02279496 -0.1383193   0.44207528 -0.7531523   2.0261486
  -0.06997604  0.85445154]
 [ 0.1175475   0.03493892 -1.5700307   0.4457582   0.10944034 -0.8035768
  -1.7166729   0.3738578  -0.14371012 -0.34646833  1.1456194  -0.416
   0.43369916  1.0241015  -0.74785167 -0.59090924 -1.2060374   0.8307429
   1.0951619   1.3672234 ]
 [-0

In [69]:
random1 = tf.random.Generator.from_seed(8)
random1 =random1.uniform(shape=(10,20)) # distributions can be normal , uniform
print(random1)

tf.Tensor(
[[0.5520444  0.10948515 0.6487982  0.9890779  0.8203654  0.70470357
  0.9578625  0.02297425 0.93598676 0.6513264  0.31663585 0.00111556
  0.9212191  0.3822806  0.77246034 0.91514194 0.5751133  0.793342
  0.4289763  0.19118965]
 [0.7452506  0.41762006 0.8173511  0.20117116 0.6457157  0.16484237
  0.4484123  0.6057888  0.816115   0.4129653  0.2632984  0.19087589
  0.7631861  0.8340243  0.49447727 0.6866319  0.300259   0.26729417
  0.83389175 0.62988555]
 [0.15143108 0.47044265 0.69402504 0.9605911  0.93813527 0.5299927
  0.21156156 0.3940668  0.16456759 0.42329657 0.6732943  0.28540838
  0.41686988 0.74725735 0.8982729  0.95173836 0.09668875 0.94335854
  0.6924689  0.98699486]
 [0.9925091  0.20401764 0.26398885 0.79402816 0.71974635 0.47845697
  0.21366036 0.78412795 0.93207085 0.5625777  0.47580373 0.30543637
  0.5387846  0.06375635 0.634938   0.6435729  0.3422103  0.8459996
  0.21559799 0.10748649]
 [0.1337657  0.95617914 0.6482675  0.55495536 0.02367401 0.74084485
  0.35598

In [70]:
random == random1

<tf.Tensor: shape=(10, 20), dtype=bool, numpy=
array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, 

# Shuffling the tensors

In [71]:
x = tf.constant([[10,11,12],[13,14,15],
                [16,17,18]])

In [72]:
tf.random.set_seed(50) # golabl level seed
tf.random.shuffle(x,seed=20) #operational level seed can be set yet gives diffrent results if the global seed is not mentioned ....it is default


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [16, 17, 18],
       [13, 14, 15]], dtype=int32)>

>tf.random.set_seed(42): Sets the global random seed, making the overall random operations in TensorFlow deterministic.

>tf.random.shuffle(x, seed=45): Sets the operation-specific seed, making this particular shuffle operation deterministic given the global seed.

> Both seeds are required to ensure that the shuffle operation produces the same result every time you run your script.

In [73]:
x = tf.ones(shape=(10,3))

In [74]:
tf.zeros(shape=(10,3))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

# using numpy


In [75]:
import numpy as np
arr = np.arange(1,25,dtype=np.float16) # default is np.int32

In [76]:
a = tf.constant(value = arr,shape=(2,3,4))
b = tf.constant(value = arr)
a,b

(<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
 array([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],
 
        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]], dtype=float16)>,
 <tf.Tensor: shape=(24,), dtype=float16, numpy=
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
       dtype=float16)>)

In [77]:
def describe(x):
  print("Shape :",x.shape)
  print("Datatype of each element : ",x.dtype)
  print("Dimensions of the element : ",x.ndim)
  print("First axis Element : ",x[0])
  print("Last axis Element : ",x[-1])
  print("Total elements : ", tf.size(x))

In [78]:
z = tf.zeros(shape=(2,3,4,5))
describe(z)

Shape : (2, 3, 4, 5)
Datatype of each element :  <dtype: 'float32'>
Dimensions of the element :  4
First axis Element :  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Last axis Element :  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Total elements :  tf.Tensor(120, shape=(), dtype=int32)


INDEXING :

In [79]:
print(z[:1,:1,:1,:1])
print(z[:1,:1,:1,:])
print(z[:1,:1,:,:1])
print(z[:,:1,:2,:3])

tf.Tensor([[[[0.]]]], shape=(1, 1, 1, 1), dtype=float32)
tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)
tf.Tensor(
[[[[0.]
   [0.]
   [0.]
   [0.]]]], shape=(1, 1, 4, 1), dtype=float32)
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]]], shape=(2, 1, 2, 3), dtype=float32)


In [80]:
x = tf.constant([[1,2],[3,4]])
print(x.ndim)

2


In [81]:
print(x)
print(x[:,-1],">>>>>>>>>",x[-1,-1])#Last Element (DONT PUT COLON BEFORE THE -1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32) >>>>>>>>> tf.Tensor(4, shape=(), dtype=int32)


# ADDING NEW DIMENSIONS IN A TENSOR

In [82]:
y = x[:,tf.newaxis,:] # WE can use tf.new axis to add a dimension in between or at the end
y = x[...,tf.newaxis] # we can use ... which indicates all the previous dimensions instead of typing <<<<<<<<<<<<<<:,:,:,:,>>>>>>>>>>>>>>>>
print(y)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


In [83]:
# Alternative Way to add axis :
tf.expand_dims(x,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

## TESNSOR OPERATIONS


Basic : +,-,/,*

In [84]:
x = x+10 # dont directly manipulate original tensor we need to assign
print(x)
x = x*10
print(x)

tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[110 120]
 [130 140]], shape=(2, 2), dtype=int32)


In [85]:
tf.multiply(y,10) #inbuilt functions for faster manipulation

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]]], dtype=int32)>

In [86]:
tf.matmul(x,x) # Inbuilt function

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27700, 30000],
       [32500, 35200]], dtype=int32)>

In [87]:
x@x #python operator

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27700, 30000],
       [32500, 35200]], dtype=int32)>

In [88]:
y = tf.constant([[1,2,3],[4,5,6]])
d = tf.constant([[7,8,9],[10,11,12]])
print(y.shape,d.shape) # we can multiply as the shapes are asymmetric and same
print(y@tf.reshape(d,shape=(3,2))) #convolved
print(y@tf.transpose(d)) # Both results in diffrent matrices as seen below

(2, 3) (2, 3)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 50  68]
 [122 167]], shape=(2, 2), dtype=int32)


In [89]:
print(d,tf.transpose(d),tf.reshape(d,shape=(3,2)))

tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) tf.Tensor(
[[ 7 10]
 [ 8 11]
 [ 9 12]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


# To Change Datatype

In [90]:
print("X : ",x,"\n Datatype : ",x.dtype)

X :  tf.Tensor(
[[110 120]
 [130 140]], shape=(2, 2), dtype=int32) 
 Datatype :  <dtype: 'int32'>


In [91]:
x = tf.cast(x,dtype=tf.float16) #convert x into float16
print("X : ",x,"\n Datatype : ",x.dtype)

X :  tf.Tensor(
[[110. 120.]
 [130. 140.]], shape=(2, 2), dtype=float16) 
 Datatype :  <dtype: 'float16'>


# Aggregating the values
* absolute
* minimum
* maximum
* mean

In [92]:
a = tf.constant([-91,10])
print(a)

tf.Tensor([-91  10], shape=(2,), dtype=int32)


In [93]:
tf.abs(a) # absolute value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([91, 10], dtype=int32)>

In [94]:
n = tf.constant(np.random.randint(0,100,size=50))
print(n)
print(n.shape,n.ndim,tf.size(n))

tf.Tensor(
[47 43 97 48 96  3 39 42 94 70 64  2 51 99 92 50 42 11 88  7 95 58 15 21
 16 61 63 19 60  9  6 70 87 49 50 93 62 45 68 56 28 99 68 67 35 43 14 32
 26 91], shape=(50,), dtype=int64)
(50,) 1 tf.Tensor(50, shape=(), dtype=int32)


In [95]:
print("Mean = ",tf.reduce_mean(n),"\n Sum = ",tf.reduce_sum(n),"\n Min = ",tf.reduce_min(n),"\n Max = ",tf.reduce_max(n))

Mean =  tf.Tensor(51, shape=(), dtype=int64) 
 Sum =  tf.Tensor(2591, shape=(), dtype=int64) 
 Min =  tf.Tensor(2, shape=(), dtype=int64) 
 Max =  tf.Tensor(99, shape=(), dtype=int64)


In [96]:
import tensorflow_probability as tfp
tfp.stats.variance(n) #numpy value


<tf.Tensor: shape=(), dtype=int64, numpy=852>

In [97]:
tf.math.reduce_std(tf.cast(n,dtype=tf.float32)) #numpy value and for std we require float value

<tf.Tensor: shape=(), dtype=float32, numpy=29.179234>

# Finding index or position of min or max element in tensor


In [98]:
print(n)
# print(tf.argmax(n))
max = tf.argmax(n)
if tf.reduce_max(n)==n[tf.argmax(n)]:
  print(f"Verified that {tf.reduce_max(n)} is the highest value at index {max}")

tf.Tensor(
[47 43 97 48 96  3 39 42 94 70 64  2 51 99 92 50 42 11 88  7 95 58 15 21
 16 61 63 19 60  9  6 70 87 49 50 93 62 45 68 56 28 99 68 67 35 43 14 32
 26 91], shape=(50,), dtype=int64)
Verified that 99 is the highest value at index 13


In [99]:
print(n)
# print(tf.argmin(n))
min = tf.argmin(n)
if tf.reduce_min(n)==n[tf.argmin(n)]:
  print(f"Verified that {tf.reduce_min(n)} is the lowest value at index {min}")

tf.Tensor(
[47 43 97 48 96  3 39 42 94 70 64  2 51 99 92 50 42 11 88  7 95 58 15 21
 16 61 63 19 60  9  6 70 87 49 50 93 62 45 68 56 28 99 68 67 35 43 14 32
 26 91], shape=(50,), dtype=int64)
Verified that 2 is the lowest value at index 11


In [100]:
print(n)
print(f"Squareing operation :\n {tf.square(n)}")
print(f"\n\nSqrt operation : (requires float values and will throw error if dtype is int32) :\n{tf.sqrt(tf.cast(n,dtype=tf.float16))}")
print(f"\n\n Log operation : (requires float values) : \n {tf.math.log(tf.cast(n,tf.float32))}")

tf.Tensor(
[47 43 97 48 96  3 39 42 94 70 64  2 51 99 92 50 42 11 88  7 95 58 15 21
 16 61 63 19 60  9  6 70 87 49 50 93 62 45 68 56 28 99 68 67 35 43 14 32
 26 91], shape=(50,), dtype=int64)
Squareing operation :
 [2209 1849 9409 2304 9216    9 1521 1764 8836 4900 4096    4 2601 9801
 8464 2500 1764  121 7744   49 9025 3364  225  441  256 3721 3969  361
 3600   81   36 4900 7569 2401 2500 8649 3844 2025 4624 3136  784 9801
 4624 4489 1225 1849  196 1024  676 8281]


Sqrt operation : (requires float values and will throw error if dtype is int32) :
[6.855 6.56  9.85  6.93  9.8   1.732 6.246 6.48  9.695 8.37  8.    1.414
 7.14  9.95  9.59  7.07  6.48  3.316 9.38  2.646 9.75  7.617 3.873 4.582
 4.    7.81  7.938 4.36  7.746 3.    2.45  8.37  9.33  7.    7.07  9.64
 7.875 6.707 8.25  7.484 5.293 9.95  8.25  8.19  5.918 6.56  3.742 5.656
 5.098 9.54 ]


 Log operation : (requires float values) : 
 [3.8501477 3.7612002 4.574711  3.871201  4.564348  1.0986123 3.6635616
 3.7376697 4.543295  4.

# Removing single redundant dimensions

In [101]:
tf.random.set_seed(89) # only works for  tensorflow
# eg = tf.constant(np.random.randint(1,100,50),shape=(1,1,1,1,50))
eg = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
print(eg.shape)

(1, 1, 1, 1, 50)


In [102]:
print(tf.squeeze(eg).shape)

(50,)


# One Hot Encoding

we can use this to encode diffrent labels of classes ,we need to passs the list of unique classes and the depth as the parameters and if we wish we can also add on and off value in the form of a text

In [103]:
li = []
# index = []
i = True
while i == True:
    c = str(input("Enter diffrent names of colors.....enter '0' after completion :  "))
    if c == "0":
        i = False
    else:
        li.append(c)
print (li)

# for i in range(len(li)) :
#     index.append(i)

index = tf.range(0,len(li))
Encoding = tf.one_hot(index,depth=5)
print(Encoding,"\n")

for i in range(len(li)):
  print(f"{li[i]} : {Encoding[i,:]}\n")


Enter diffrent names of colors.....enter '0' after completion :  a
Enter diffrent names of colors.....enter '0' after completion :  b
Enter diffrent names of colors.....enter '0' after completion :  0
['a', 'b']
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]], shape=(2, 5), dtype=float32) 

a : [1. 0. 0. 0. 0.]

b : [0. 1. 0. 0. 0.]



In [104]:
Encoding = tf.one_hot(index,depth=5,on_value = "Vedant",off_value="Ranade") # 1 is vedant,0 is ranade
print(Encoding,"\n")

tf.Tensor(
[[b'Vedant' b'Ranade' b'Ranade' b'Ranade' b'Ranade']
 [b'Ranade' b'Vedant' b'Ranade' b'Ranade' b'Ranade']], shape=(2, 5), dtype=string) 



# Numpy operations


In [116]:
num = tf.constant(np.array(np.random.uniform(5,10,10))) # or jisme jisme numpy use hoga
t = tf.constant([9.,3.,4.])

print(f"There is diffrence in defualt dtype\n 1) Numpy : {num.dtype} \n 2) Direct {t.dtype}")

There is diffrence in defualt dtype
 1) Numpy : <dtype: 'float64'> 
 2) Direct <dtype: 'float32'>


In [119]:
# we can access it easily
num.numpy()[0]


6.428742171005208