In [43]:
import tensorflow as tf

In [44]:
tf.__version__

'2.15.0'

In [45]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim) #number of dimensions

tf.Tensor(7, shape=(), dtype=int32)
0


In [46]:
vector = tf.constant([26,12])
print(vector)
print(vector.ndim) #number of dimensions

tf.Tensor([26 12], shape=(2,), dtype=int32)
1


In [47]:
matrix = tf.constant([[26,12],[9,11]])
print(matrix)
print(matrix.ndim) #number of dimensions

tf.Tensor(
[[26 12]
 [ 9 11]], shape=(2, 2), dtype=int32)
2


In [48]:
matrix = tf.constant([[26,12],[9,11]],dtype =tf.float16) #chnaging dtype
print(matrix)
print(matrix.ndim) #number of dimensions

tf.Tensor(
[[26. 12.]
 [ 9. 11.]], shape=(2, 2), dtype=float16)
2


# tf.Variable()

In [69]:
changeable_tensor = tf.Variable([13, 34])
unchanageble = tf.constant([12,26])

In [70]:
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([13, 34], dtype=int32)>


In [71]:
# changeable_tensor.append([12,26]) ..........NO append works for this instead use assign
# print(changeable_tensor)

In [72]:
# Now you can use .assign()
changeable_tensor[0].assign(12,67)
print(changeable_tensor)

# We can use assign() on unchanagable tensors or constants which are specially designed to keep the tensor value consistent

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12, 34], dtype=int32)>
