In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

In [ ]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim) #number of dimensions

tf.Tensor(7, shape=(), dtype=int32)
0


In [ ]:
vector = tf.constant([26,12])
print(vector)
print(vector.ndim) #number of dimensions

tf.Tensor([26 12], shape=(2,), dtype=int32)
1


In [ ]:
matrix = tf.constant([[26,12],[9,11]])
print(matrix)
print(matrix.ndim) #number of dimensions

tf.Tensor(
[[26 12]
 [ 9 11]], shape=(2, 2), dtype=int32)
2


In [ ]:
matrix = tf.constant([[26,12],[9,11]],dtype =tf.float16) #chnaging dtype
print(matrix)
print(matrix.ndim) #number of dimensions

tf.Tensor(
[[26. 12.]
 [ 9. 11.]], shape=(2, 2), dtype=float16)
2


# tf.Variable()

In [ ]:
changeable_tensor = tf.Variable([13, 34])
unchanageble = tf.constant([12,26])

In [ ]:
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([13, 34], dtype=int32)>


In [ ]:
# changeable_tensor.append([12,26]) ..........NO append works for this instead use assign
# print(changeable_tensor)

In [ ]:
# Now you can use .assign()
changeable_tensor[0].assign(12,67)
print(changeable_tensor)

# We can use assign() on unchanagable tensors or constants which are specially designed to keep the tensor value consistent

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12, 34], dtype=int32)>


### Random Tensor

In [7]:
random = tf.random.Generator.from_seed(8)
random =random.normal(shape=(10,20)) # distributions can be normal , uniform
print(random)

tf.Tensor(
[[ 0.69211644  0.84215707 -0.06378496  0.92800784 -0.6039789  -0.1766927
   0.04221033  0.29037967 -0.29604465 -0.21134205  0.01063002  1.5165398
   0.27305737 -0.29925638 -0.3652325   0.61883307 -1.0130816   0.28291714
   1.2132233   0.46988967]
 [ 0.37944323 -0.6664026   0.6054596   0.19181173  0.8045827   0.4769051
  -0.7812124  -0.996891    0.33149973 -0.5445254   1.5222508   0.59303206
  -0.63509274  0.3703566  -1.0939722  -0.4601445   1.5420506  -0.16822556
  -0.4390865  -0.4129243 ]
 [ 0.35877243 -1.9095894  -0.2094769   0.8286217  -0.06695071 -0.35105535
   1.0884082  -1.3863064   0.88051325 -1.6833194   0.86754173 -0.19625713
  -1.322665   -0.02279496 -0.1383193   0.44207528 -0.7531523   2.0261486
  -0.06997604  0.85445154]
 [ 0.1175475   0.03493892 -1.5700307   0.4457582   0.10944034 -0.8035768
  -1.7166729   0.3738578  -0.14371012 -0.34646833  1.1456194  -0.416
   0.43369916  1.0241015  -0.74785167 -0.59090924 -1.2060374   0.8307429
   1.0951619   1.3672234 ]
 [-0

In [8]:
random1 = tf.random.Generator.from_seed(8)
random1 =random1.uniform(shape=(10,20)) # distributions can be normal , uniform
print(random1)

tf.Tensor(
[[0.5520444  0.10948515 0.6487982  0.9890779  0.8203654  0.70470357
  0.9578625  0.02297425 0.93598676 0.6513264  0.31663585 0.00111556
  0.9212191  0.3822806  0.77246034 0.91514194 0.5751133  0.793342
  0.4289763  0.19118965]
 [0.7452506  0.41762006 0.8173511  0.20117116 0.6457157  0.16484237
  0.4484123  0.6057888  0.816115   0.4129653  0.2632984  0.19087589
  0.7631861  0.8340243  0.49447727 0.6866319  0.300259   0.26729417
  0.83389175 0.62988555]
 [0.15143108 0.47044265 0.69402504 0.9605911  0.93813527 0.5299927
  0.21156156 0.3940668  0.16456759 0.42329657 0.6732943  0.28540838
  0.41686988 0.74725735 0.8982729  0.95173836 0.09668875 0.94335854
  0.6924689  0.98699486]
 [0.9925091  0.20401764 0.26398885 0.79402816 0.71974635 0.47845697
  0.21366036 0.78412795 0.93207085 0.5625777  0.47580373 0.30543637
  0.5387846  0.06375635 0.634938   0.6435729  0.3422103  0.8459996
  0.21559799 0.10748649]
 [0.1337657  0.95617914 0.6482675  0.55495536 0.02367401 0.74084485
  0.35598

In [9]:
random == random1

<tf.Tensor: shape=(10, 20), dtype=bool, numpy=
array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, 

# Shuffling the tensors

In [11]:
x = tf.constant([[10,11,12],[13,14,15],
                [16,17,18]])

In [31]:
tf.random.set_seed(50) # golabl level seed
tf.random.shuffle(x,seed=20) #operational level seed can be set yet gives diffrent results if the global seed is not mentioned ....it is default


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [16, 17, 18],
       [13, 14, 15]], dtype=int32)>

>tf.random.set_seed(42): Sets the global random seed, making the overall random operations in TensorFlow deterministic.

>tf.random.shuffle(x, seed=45): Sets the operation-specific seed, making this particular shuffle operation deterministic given the global seed.

> Both seeds are required to ensure that the shuffle operation produces the same result every time you run your script.

In [32]:
x = tf.ones(shape=(10,3))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [37]:
tf.zeros(shape=(10,3))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

# using numpy


In [41]:
import numpy as np
arr = np.arange(1,25,dtype=np.float16) # default is np.int32

In [46]:
a = tf.constant(value = arr,shape=(2,3,4))
b = tf.constant(value = arr)
a,b

(<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
 array([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],
 
        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]], dtype=float16)>,
 <tf.Tensor: shape=(24,), dtype=float16, numpy=
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
       dtype=float16)>)

In [56]:
def describe(x):
  print("Shape :",x.shape)
  print("Datatype of each element : ",x.dtype)
  print("Dimensions of the element : ",x.ndim)
  print("First axis Element : ",x[0])
  print("Last axis Element : ",x[-1])
  print("Total elements : ", tf.size(x))

In [57]:
z = tf.zeros(shape=(2,3,4,5))
describe(z)

Shape : (2, 3, 4, 5)
Datatype of each element :  <dtype: 'float32'>
Dimensions of the element :  4
First axis Element :  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Last axis Element :  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Total elements :  tf.Tensor(120, shape=(), dtype=int32)
